### ISSUE TITLE
Parse date from given text.

### ISSUE THREAD

**Issue by dhanrajdc7** [kaboc/dart_text_parser#4]
A natural language date parser, designed to extract date information from any given text.

Text -> "Bring a book on December 1" -> should return Date ->  "Dec 1, 2021, 12:00 PM"

I have used [SwiftyChrono](https://github.com/quire-io/SwiftyChrono) in iOS for date parsing but struggling to code it in dart & flutter. I would be happy if your text parser also provides this feature.

**Comment by kaboc** [comment]
Thanks for your request!

I checked the SwiftyChrono page and learnt that it was specialised in parsing dates. On the other hand, this text_parser package is something like a wrapper of `RegExp` for more general purposes, not for such a specific usage as yours. Therefore I'd rather keep it simple without adding the feature.

But it's still not completely impossible with this package like below:

```dart
class DateMatcher extends TextMatcher {
  const DateMatcher()
      : super(
          r'(?:january|february|march|april|may|june|july|august|'
          r'september|october|november|december) \d{1,2}',
        );
}
```

```dart
import 'package:intl/intl.dart';
import 'package:text_parser/text_parser.dart';

Future<void> main() async {
  const text = 'Bring a book on December 1';

  final parser = TextParser(
    matchers: const [DateMatcher()],
    caseSensitive: false,
  );
  final elements = await parser.parse(text, onlyMatches: true);  // [matcherType: DateMatcher, text: December 1, groups: []]

  for (final date in elements) {
    final dateTime = DateFormat('MMMM dd yyyy').parse('${date.text} 2021');
    print(dateTime);  // 2021-12-01 00:00:00.000
  }
}
```

The date format varies depending on the language/country/region like `December 1`, `1 December`, `12/1`, etc, so you'll need to tweak the format and the regexp pattern.

**Comment by dhanrajdc7** [comment]
Ok, Thank you @kaboc 
I got the idea, how to do with Text_Parser Package. Thank you.
